CREATE TABLE teams (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    points FLOAT NOT NULL,
    teamname TEXT NOT NULL,
    builders TEXT NOT NULL
);

CREATE TABLE scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winner INTEGER NOT NULL
);